# Generated by Django 5.1.6 on 2025-03-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField()),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('backdrop_url', models.URLField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(choices=[('catalogo', 'Catalogo'), ('estreno', 'Estreno')], default='catalogo', max_length=10)),
                ('audio', models.CharField(choices=[('sub', 'Subtitulado'), ('lat', 'Latino'), ('cast', 'Castellano'), ('dual', 'Dual')], max_length=20)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=6, null=True)),
                ('video_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='movies', to='dashboard.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
