# Generated by Django 5.1.6 on 2025-03-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Tipo de contenido', 'verbose_name_plural': 'Tipos de contenido'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-id'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
    ]
